version: '3'
services:
  db:
    image: mysql:8.3
    container_name: storyboard_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${SQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
    env_file:
      - environmentfile
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: storyboard_backend
    command: sh -c "python3 manage.py migrate --noinput 
      && python3 manage.py collectstatic --noinput
      && python manage.py createsuperuser --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL --noinput || true
      && python manage.py runserver 0.0.0.0:8000
      "
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media/
    env_file:
      - .docker.env
volumes:
  data:
  media: