# Generated by Django 5.0 on 2024-03-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveStoryContestModel',
            fields=[
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='painter.story')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='LockedStoryContestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter.story')),
                ('winning_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter.image')),
            ],
        ),
        migrations.CreateModel(
            name='LockedStoryContestImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='painter.image')),
                ('story_contest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='painter.lockedstorycontestmodel')),
            ],
            options={
                'ordering': ['votes'],
            },
        ),
        migrations.CreateModel(
            name='StoryContestImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='painter.image')),
                ('story_contest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='painter.activestorycontestmodel')),
            ],
            options={
                'ordering': ['votes'],
            },
        ),
    ]
