# Generated by Django 5.0 on 2024-03-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='started_by',
        ),
    ]
