# Generated by Django 5.0 on 2024-03-14 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activestorycontestmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lockedstorycontestmodel',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='activestorycontestmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='lockedstorycontestmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
