# Generated by Django 5.0 on 2024-03-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0002_alter_activestorycontestmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storycontestimagemodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='storycontestimagemodel',
            name='votes',
        ),
        migrations.AlterField(
            model_name='lockedstorycontestimagemodel',
            name='votes',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StoryContestImageModelVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='painter.storycontestimagemodel')),
            ],
        ),
    ]
