# Generated by Django 5.0 on 2024-03-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0003_alter_storycontestimagemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lockedstorycontestimagemodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='lockedstorycontestimagemodel',
            name='votes',
        ),
        migrations.AlterField(
            model_name='lockedstorycontestimagemodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='painter.image'),
        ),
        migrations.AlterField(
            model_name='lockedstorycontestimagemodel',
            name='story_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter.lockedstorycontestmodel'),
        ),
        migrations.AlterField(
            model_name='lockedstorycontestmodel',
            name='winning_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='painter.image'),
        ),
        migrations.AlterField(
            model_name='storycontestimagemodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='painter.image'),
        ),
        migrations.AlterField(
            model_name='storycontestimagemodel',
            name='story_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter.activestorycontestmodel'),
        ),
        migrations.AlterField(
            model_name='storycontestimagemodelvote',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter.storycontestimagemodel'),
        ),
        migrations.CreateModel(
            name='CloseStoryContestModelVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter.activestorycontestmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LockedCloseStoryContestModelVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter.lockedstorycontestmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LockedStoryContestImageModelVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter.lockedstorycontestimagemodel')),
            ],
        ),
    ]
