# Generated by Django 5.0 on 2024-03-20 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0005_remove_lockedstorycontestimagemodelvote_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
